### ISSUE TITLE
:sparkles: Add option to have custom format dates

### ISSUE THREAD

**Issue by lyntco** [one19/todo-month#1]
It'd be nice to be able to customise the date format!

**Comment by one19** [comment]
I'd like to come up with a wholistic solution to fix #4 and this at the same time

**Comment by lyntco** [comment]
I think we could use moment.js to have formatting any way a person likes the same system moment uses. This way it does not need to be specced or maintained.
It'd also solve #4 if a use could configure any format they wanted for weekends/ weekdays

**Comment by one19** [comment]
Ive created that pull request to hopefully solve the issue, without having something as weighty as moment floating about? What do you think?
