### ISSUE TITLE
Consistent name days

### ISSUE THREAD

**Issue by Scoutski** [one19/todo-month#4]
At the moment the output shows "SATURDAY" and "SUNDAY" on the weekends and then a 2 letter acronym during the week. If this is intended, can you add a flag for consistency

Example:
### 01-06-2017 - SATURDAY
- 
### 02-06-2017 - SUNDAY
- 
### 03-06-2017 - Mo
- 
### 04-06-2017 - Tu
- 

Impact:
Critical

**Comment by lyntco** [comment]
🚨

**Comment by one19** [comment]
Good catch! I've created a PR that will hopefully fix this issue, let me know what you think!

**Comment by Scoutski** [comment]
Perhaps this is a chance for a --full-names flag?

**Comment by one19** [comment]
The readme isn't super clear, but you can get the same thing with `-f dd-mm-yyyy - dddd`
